# Data Preprocessing Tools

## Importing the libraries

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [17]:
dataset=pd.read_csv("Data.csv") # csv dosyasını alıp dataFrame olarak içe aktarır
X=dataset.iloc[:,:-1].values # Son sütuna KADAR tüm sütunları al son sütun hariç, ilk kısımda ise satırlar belirtilir
y=dataset.iloc[:,-1].values # Sadece son sütunu alır tüm satırlarla birlikte

In [18]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [19]:
from sklearn.impute import SimpleImputer # Eksik verileri ortalama veya medyan ile doldurmak için kullanacağımız Class
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') # tüm NaN verileri ortalama ile dolduracağımızı belirttik
imputer.fit(X[:,1:3]) # 1. sütun dışındaki diğer 2 sütunu tüm satırları ile alır ve ortalama ile doldurur
X[:,1:3]=imputer.transform(X[:,1:3]) # değişiklikleri uygular


In [20]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough') 
#kısaca her birine farklı ID verdik
#transformers kısmında hangi sütunun değişeceğini ve hangi classla değiştireceğimizi belirttik
# remainder kısmında değiştirilmeyen kısımların ne olacağını seçtik 'passthrough' aynı şekilde kalacağını 
#ve silinmeyeceğini belirtir
X=np.array(ct.fit_transform(X)) # fit transform bize np array döndürmediği için ve np array Model kısmında zorunlu olduğu için dönüşüm yaptık
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Independent Variable

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y) # burada ise kısaca değişkenimizi 0 ve 1 lere dönüştürdük. Aradaki fark onehot multiple label ikili
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
#verileri %80 train %20 test olarak böldük. Bu klasik train test formatıdır.
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


## Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[:,3:]=scaler.fit_transform(X_train[:,3:]) #3'ten sonraki tüm kolonları alır. ve ortalama ile sapmayı hesaplar(fit)ve uygular(transform)
X_test[:,3:]=scaler.transform(X_test[:,3:])# fitlemeden (hesaplamadan) sadece dönüştürdük (transform)
# Ülke değişkeni için scaling uygulamak saçma çünkü kategorik.
# X_Train için fit yaptığımız yani oradaki ortalama ve standartSapmayı alarak formülü x_test için ayrı olarak uyguladık
# bu sayede x test verileri ayrı tutuldu ve bilgi sızıntısı yaşanmadı
print(X_train)
print(X_test)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
